caaaaaady_abood = ("Anime lover", "Writer", "Doesn't listener", "Academic freak but not like portia level", "Friend")

caaaaaady_abood.append("Child of tyler daddy")
print(caaaaaady_abood)
caaaaaady_abood.insert(4, "Fancy dresser but denies it")
print(caaaaaady_abood)
caaaaaady_abood.remove("Friend")
print(caaaaaady_abood)
caaaaaady_abood.pop([3])
print(caaaaaady_abood)
caaaaaady_abood.index(2)
print(caaaaaady_abood)
caaaaaady_abood.count(4)
print(caaaaaady_abood)
caaaaaady_abood.sort(1)
print(caaaaaady_abood)